# Generated by Django 4.1 on 2022-09-29 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GioVao', models.DateField(null=True)),
                ('GioiRa', models.DateField(null=True)),
                ('TrangThai', models.CharField(max_length=200, null=True)),
                ('SoLuongKhach', models.IntegerField()),
                ('NgayDatPhong', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=200, null=True)),
                ('SoDienThoai', models.IntegerField()),
                ('ThanhPho', models.CharField(max_length=200, null=True)),
                ('QuocGia', models.CharField(max_length=200, null=True)),
                ('MaBuuDien', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoDienThoai', models.IntegerField()),
                ('QuocGia', models.CharField(max_length=200, null=True)),
                ('MaBuuDien', models.CharField(max_length=200, null=True)),
                ('ThanhPho', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoaiPhong', models.CharField(max_length=200, null=True)),
                ('GiaPhong', models.CharField(max_length=200, null=True)),
                ('ViTriPhong', models.CharField(max_length=200, null=True)),
                ('SoLuongGiuong', models.IntegerField()),
                ('KhachHang_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TienPhong', models.IntegerField()),
                ('CacKhoanPhiKhac', models.IntegerField()),
                ('SoTheTinDung', models.IntegerField()),
                ('NgayThanhToan', models.DateField(null=True)),
                ('KhachHang_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenDichVu', models.CharField(max_length=200, null=True)),
                ('GiaDichVu', models.IntegerField()),
                ('DatPhong_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.datphong')),
            ],
        ),
        migrations.AddField(
            model_name='datphong',
            name='Phong_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phong'),
        ),
    ]
