# Generated by Django 4.1 on 2022-09-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datphong',
            name='Phong_id',
        ),
        migrations.RemoveField(
            model_name='dichvu',
            name='DatPhong_id',
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='KhachHang_id',
        ),
        migrations.DeleteModel(
            name='KhachSan',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='KhachHang_id',
        ),
        migrations.DeleteModel(
            name='DatPhong',
        ),
        migrations.DeleteModel(
            name='DichVu',
        ),
        migrations.DeleteModel(
            name='HoaDon',
        ),
        migrations.DeleteModel(
            name='KhachHang',
        ),
        migrations.DeleteModel(
            name='Phong',
        ),
    ]
