# Generated by Django 4.1 on 2022-10-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_khachhang_nguoithamgiakhaosat_nhanvienkinhdoanh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoithamgiakhaosat',
            name='username',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
