# Generated by Django 4.1 on 2022-10-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_nguoithamgiakhaosat_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvienkinhdoanh',
            name='username',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
