# Generated by Django 4.1 on 2022-10-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_nhanvienkinhdoanh_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvienkinhdoanh',
            name='suakhachhang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nhanvienkinhdoanh',
            name='themkhachhang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nhanvienkinhdoanh',
            name='xoakhachhang',
            field=models.BooleanField(default=False),
        ),
    ]
