# Generated by Django 4.1 on 2022-10-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_khachhang_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='kichhoat',
            field=models.BooleanField(default=False),
        ),
    ]
