# Generated by Django 4.1 on 2022-10-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_khachhang_kichhoat'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='forget_password_token',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvienkinhdoanh',
            name='forget_password_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
