# Generated by Django 4.1 on 2022-10-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_khachhang_forget_password_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='email',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nguoithamgiakhaosat',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvienkinhdoanh',
            name='email',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
