# Generated by Django 4.1 on 2022-10-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_khachhang_email_nguoithamgiakhaosat_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='thamgiakhaosat',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
