# Generated by Django 4.1 on 2022-10-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_khachhang_thamgiakhaosat'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoithamgiakhaosat',
            name='sodienthoai',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
