# Generated by Django 4.1 on 2022-10-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_nguoithamgiakhaosat_sodienthoai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='thamgiakhaosat',
        ),
        migrations.AddField(
            model_name='nguoithamgiakhaosat',
            name='thamgiakhaosat',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
