# Generated by Django 4.1 on 2022-10-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_nhanvienkinhdoanh_manhanvien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datataikhoankhachhangthem', models.CharField(max_length=100)),
                ('dathem', models.BooleanField(default=False)),
            ],
        ),
    ]
