# Generated by Django 4.1 on 2022-10-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='dathem',
        ),
    ]
