# Generated by Django 4.1 on 2022-10-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_admin_dathem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminPheDuyet',
        ),
    ]
