# Generated by Django 4.1 on 2022-10-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_admin_adminpheduyet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPheDuyetKhachHangThem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datataikhoankhachhangthem', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminPheDuyet',
        ),
    ]
