# Generated by Django 4.1 on 2022-10-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_datataikhoankhachhangsua_adminpheduyetkhachhangsua_diachi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiKhaoSat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('KhaoSatSo', models.IntegerField(default=0)),
                ('DuLieuKhaoSat', models.TextField(default='')),
            ],
        ),
    ]
