# Generated by Django 4.1 on 2022-10-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_baikhaosat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baikhaosat',
            old_name='username',
            new_name='username_khachhang',
        ),
    ]
