# Generated by Django 4.1 on 2022-10-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_username_baikhaosat_username_khachhang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baikhaosat',
            old_name='DuLieuKhaoSat',
            new_name='dulieukhaosat',
        ),
        migrations.RenameField(
            model_name='baikhaosat',
            old_name='KhaoSatSo',
            new_name='khaosatso',
        ),
    ]
