# Generated by Django 4.1 on 2022-10-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_dulieukhaosat_baikhaosat_dulieukhaosat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='taocuockhaosat',
            field=models.BooleanField(default=False),
        ),
    ]
