# Generated by Django 4.1 on 2022-10-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_khachhang_taocuockhaosat'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='khaosat_token',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
