# Generated by Django 4.1 on 2022-10-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_khachhang_khaosat_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='khaosat_token',
        ),
        migrations.AddField(
            model_name='nguoithamgiakhaosat',
            name='khaosat_token',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
