# Generated by Django 4.1 on 2022-10-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_khachhang_khaosat_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoithamgiakhaosat',
            name='ketquakhaosat',
            field=models.TextField(default=''),
        ),
    ]
