# Generated by Django 4.1 on 2022-10-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_nguoithamgiakhaosat_ketquakhaosat'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoithamgiakhaosat',
            name='tien',
            field=models.IntegerField(default=0),
        ),
    ]
