# Generated by Django 4.1 on 2022-10-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_adminpheduyetkhachhangsua_giatien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpheduyetkhachhangthem',
            name='giatien',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='giatien',
            field=models.IntegerField(default=0),
        ),
    ]
