# Generated by Django 4.1 on 2022-10-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_adminpheduyetkhachhangthem_giatien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoithamgiakhaosat',
            name='pheduyet',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
