# Generated by Django 4.1 on 2022-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_nguoithamgiakhaosat_pheduyet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoithamgiakhaosat',
            name='pheduyet',
        ),
        migrations.AddField(
            model_name='baikhaosat',
            name='pheduyet',
            field=models.BooleanField(default=False),
        ),
    ]
