# Generated by Django 4.1 on 2022-10-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_nguoithamgiakhaosat_pheduyet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPheDuyetBaiKhaoSat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dulieukhaosat', models.TextField()),
                ('username_khachang', models.CharField(max_length=100)),
                ('khaosatso', models.CharField(max_length=100)),
            ],
        ),
    ]
