# Generated by Django 4.1 on 2022-10-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_adminpheduyetbaikhaosat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpheduyetbaikhaosat',
            old_name='username_khachang',
            new_name='username_khachhang',
        ),
    ]
