# Generated by Django 4.1 on 2022-10-10 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_username_khachang_adminpheduyetbaikhaosat_username_khachhang'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminPheDuyetBaiKhaoSat',
            new_name='NhanVienPheDuyetBaiKhaoSat',
        ),
    ]
