# Generated by Django 4.1 on 2022-10-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_nhanvienpheduyetbaikhaosat_dulieukhaosat'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaiTroTaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('laquantrivien', models.BooleanField(default=False)),
                ('lanhanvienkinhdoanh', models.BooleanField(default=False)),
                ('lakhachhang', models.BooleanField(default=False)),
                ('languoithamgiakhaosat', models.BooleanField(default=False)),
            ],
        ),
    ]
