# Generated by Django 4.1 on 2022-10-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_adminpheduyetkhachhangxoa_nhanvienpheduyetkhachhangxoa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='vaitro',
        ),
        migrations.RemoveField(
            model_name='nguoithamgiakhaosat',
            name='vaitro',
        ),
        migrations.RemoveField(
            model_name='nhanvienkinhdoanh',
            name='vaitro',
        ),
    ]
