# Generated by Django 4.1 on 2022-10-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_khachhang_vaitro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='diachinew',
        ),
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='emailnew',
        ),
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='giatiennew',
        ),
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='hotennew',
        ),
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='kichhoatnew',
        ),
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='madinhdanhnew',
        ),
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='makhachhangnew',
        ),
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='motanoidungyeucaunew',
        ),
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='passwordnew',
        ),
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='socaukhaosatnew',
        ),
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='sodienthoainew',
        ),
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='soluongkhaosatnew',
        ),
        migrations.RemoveField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='usernamenew',
        ),
        migrations.AlterField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='giatien',
            field=models.CharField(max_length=100),
        ),
    ]
