# Generated by Django 4.1 on 2022-10-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_quantrivienpheduyetkhachhangsua_diachinew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantrivienpheduyetkhachhangsua',
            name='username_old',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
