# Generated by Django 4.1 on 2022-10-13 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_quantrivienpheduyetkhachhangsua_username_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantrivien',
            name='vaitro',
        ),
    ]
