# Generated by Django 4.1 on 2022-10-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_remove_quantrivien_vaitro'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='covaitro',
            field=models.BooleanField(default=False),
        ),
    ]
