# Generated by Django 4.1 on 2022-10-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_nguoithamgiakhaosat_covaitro'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvienkinhdoanh',
            name='covaitro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quantrivien',
            name='covaitro',
            field=models.BooleanField(default=False),
        ),
    ]
