# Generated by Django 4.1 on 2022-10-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_nhanvienkinhdoanh_covaitro_quantrivien_covaitro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhanvienpheduyetkhachhangxoa',
            old_name='datataikhoankhachhangxoa',
            new_name='username',
        ),
    ]
