# Generated by Django 4.1 on 2022-10-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_hangdoiquantrivienpheduyet_hanhdongpheduyet'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoithamgiakhaosat',
            name='forget_password_token',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
