# Generated by Django 4.1 on 2022-10-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_nguoithamgiakhaosat_forget_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvienpheduyetbaikhaosat',
            name='nhanvienquanly',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
